name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get PR diff
        id: diff
        run: |
          # PR diff'ini al
          gh pr diff ${{ github.event.pull_request.number }} > pr.diff
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Trigger AI Review
        run: |
          # MCP Server'a webhook gönder
          curl -X POST ${{ secrets.REVIEW_SERVER_URL }}/webhook \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: pull_request" \
            -H "X-GitHub-Delivery: ${{ github.run_id }}" \
            -d @- << 'EOF'
          {
            "action": "${{ github.event.action }}",
            "pull_request": {
              "id": ${{ github.event.pull_request.id }},
              "number": ${{ github.event.pull_request.number }},
              "title": "${{ github.event.pull_request.title }}",
              "html_url": "${{ github.event.pull_request.html_url }}",
              "diff_url": "${{ github.event.pull_request.diff_url }}",
              "head": {
                "sha": "${{ github.event.pull_request.head.sha }}"
              }
            },
            "repository": {
              "full_name": "${{ github.repository }}",
              "name": "${{ github.event.repository.name }}",
              "owner": {
                "login": "${{ github.repository_owner }}"
              }
            }
          }
          EOF
      
      - name: Comment status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 AI Code Review başlatıldı! Sonuçlar birazdan gelecek...'
            })
